artifact_uri: file:///C:/Users/Flo/S9/Applications%20of%20Big%20Data/Project/mlruns/0/1cd1d3d077a24f9da10b7f973b779503/artifacts
end_time: 1637072887222
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 1cd1d3d077a24f9da10b7f973b779503
run_uuid: 1cd1d3d077a24f9da10b7f973b779503
source_name: ''
source_type: 4
source_version: ''
start_time: 1637072859600
status: 3
tags: []
user_id: Flo
