artifact_uri: file:///C:/Users/Flo/S9/Applications%20of%20Big%20Data/Project/mlruns/0/02d64ba3cfd240028b9f05c1008ac8c9/artifacts
end_time: 1637665700794
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 02d64ba3cfd240028b9f05c1008ac8c9
run_uuid: 02d64ba3cfd240028b9f05c1008ac8c9
source_name: ''
source_type: 4
source_version: ''
start_time: 1637665682273
status: 3
tags: []
user_id: Flo
