artifact_uri: file:///C:/Users/Flo/S9/Applications%20of%20Big%20Data/Project/mlruns/0/2b72b84477bd4fbf8bc8c047299c1c94/artifacts
end_time: 1637665804143
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 2b72b84477bd4fbf8bc8c047299c1c94
run_uuid: 2b72b84477bd4fbf8bc8c047299c1c94
source_name: ''
source_type: 4
source_version: ''
start_time: 1637665795998
status: 3
tags: []
user_id: Flo
